### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Bagerter** [ivstiv/nginx-monitor#1]
92: Illegal number: currConnections
I have this error. Help pls

**Comment by ivstiv** [comment]
Can you check the output of this command
`curl -s 127.0.0.1/nginx_status` it seems like you can't fetch the nginx statistics.

**Comment by Bagerter** [comment]
![B59F02ED-1AA1-4A72-B981-DA404BF7E2A0](https://user-images.githubusercontent.com/111465276/185770869-c53c3aef-e244-4beb-839e-84240db16712.jpeg)

**Comment by ivstiv** [comment]
Thanks for the feedback, I have made a silly mistake which is now fixed. Don't hesitate to open another issue if you find more problems.


I also noticed from your screenshot that you are not fetching the paused state of the firewall rule probably due to misconfiguration. I added a [new section](https://github.com/ivstiv/nginx-monitor#creating-a-token) to the README for creating an API token with the right permissions. You might want to double check that. 

An example of a correct output: `- Rule Legacy paused: true`. Mind the missing true/false value on your screenshot. I am silencing the error which is something that I should probably improve.
